[project]
name = "multi-agents"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "fastmcp>=2.14.5",
    "google-adk>=1.23.0",
    "litellm>=1.81.3",
]
